language: android

before_install:
  - yes | sdkmanager "platforms;android-27"

android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-27
  licenses:
    - android-sdk-license-.+
    - '.+'

jdk:
  - oraclejdk8

notifications:
  email: false

sudo: false

script:
   - ./gradlew loggerlib:build